apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: paymybuddy
spec:
  type: ClusterIP
  selector:
    app: paymybuddy
    tier: mysql
  ports:
    - port: 3306
      targetPort: 3306