apiVersion: v1
kind: Service
metadata:
  name: paymybuddy
spec:
  type: NodePort
  selector:
    app: paymybuddy
    tier: webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30088